In [20]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
mnist = input_data.read_data_sets('mnist_data/',one_hot = True)

sess = tf.InteractiveSession()
def weights_variables(shape):
    initial = tf.truncated_normal(shape, stddev = 0.1)
    return tf.Variable(initial)

def bias_variables(shape):
    initial = tf.constant( 0.1, shape = shape)
    return tf.Variable(initial)

def conv2d( x, W):
    return tf.nn.conv2d( x, W, strides = [1,1,1,1], padding = 'SAME')

def max_pool_2x2(x):
    return tf.nn.max_pool( x, ksize = [1,2,2,1], strides = [1,2,2,1], padding = 'SAME')

x = tf.placeholder( tf.float32, [None,784])
y_ = tf.placeholder( tf.float32, [None, 10])
x_images = tf.reshape(x , [-1,28,28,1])

W_conv1 = weights_variables([5,5,1,32])
b_conv1 = bias_variables([32])
h_conv1 = tf.nn.relu(conv2d(x_images , W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)

W_conv2 = weights_variables([5,5,32,64])
b_conv2 = bias_variables([64])
h_conv2 = tf.nn.relu(conv2d(h_pool1 , W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

W_fc1 = weights_variables([7*7*64,1024])
b_fc1 = bias_variables([1024])
h_pool2_flat = tf.reshape(h_pool2 , [-1,7*7*64])
h_fc1 = tf.nn.relu( tf.matmul(h_pool2_flat , W_fc1) + b_fc1)

keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout( h_fc1 , keep_prob)

W_fc2 = weights_variables([1024,10])
b_fc2 =bias_variables([10])
y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop , W_fc2) + b_fc2)

cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y_conv), reduction_indices= [1]))
train_step = tf.train.AdamOptimizer(0.0001).minimize(cross_entropy)

correct_prediction = tf.equal(tf.argmax(y_conv,1),tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast( correct_prediction , tf.float32))

tf.global_variables_initializer().run()
for i in range(2000):
    batch = mnist.train.next_batch(100)
    if i%500 == 0 :
        train_acurracy = accuracy.eval(feed_dict = { x : batch[0] , y_ : batch[1] , keep_prob : 1.0})
        print( 'step %d ,training accuracy %g '%(i , train_acurracy))
    train_step.run(feed_dict = { x : batch[0] , y_ : batch[1] , keep_prob : 0.5})
    
print('test accuracy %g '%accuracy.eval(feed_dict = { x : mnist.test.images , y_ : mnist.test.labels , keep_prob : 1.0}))

Extracting mnist_data/train-images-idx3-ubyte.gz
Extracting mnist_data/train-labels-idx1-ubyte.gz
Extracting mnist_data/t10k-images-idx3-ubyte.gz
Extracting mnist_data/t10k-labels-idx1-ubyte.gz


ResourceExhaustedError: OOM when allocating tensor of shape [3136,1024] and type float
	 [[Node: Variable_20/Adam/Initializer/zeros = Const[_class=["loc:@Variable_20"], dtype=DT_FLOAT, value=Tensor<type: float shape: [3136,1024] values: [0 0 0]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'Variable_20/Adam/Initializer/zeros', defined at:
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-9c9ac961c423>", line 47, in <module>
    train_step = tf.train.AdamOptimizer(0.0001).minimize(cross_entropy)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 325, in minimize
    name=name)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/training/adam.py", line 132, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 725, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 277, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 701, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 93, in __call__
    return array_ops.zeros(shape, dtype)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1401, in zeros
    output = constant(zero, shape=shape, dtype=dtype, name=name)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 106, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/a503wangsiqi/.conda/envs/photo/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [3136,1024] and type float
	 [[Node: Variable_20/Adam/Initializer/zeros = Const[_class=["loc:@Variable_20"], dtype=DT_FLOAT, value=Tensor<type: float shape: [3136,1024] values: [0 0 0]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]


In [7]:
import mnist_reconition as mr

s_features, s_labels = mr.re_showdigits(1)

random_test_predictions = sess.run(tf.nn.top_k(y_conv, 10),feed_dict={x: s_features, y_: s_labels , keep_prob : 1.0})
print(random_test_predictions)

SyntaxError: Non-ASCII character '\xe5' in file mnist_reconition.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (mnist_reconition.py, line 12)

In [3]:
a=[[1,2,3]]
b=[[1,1,1]]

In [4]:
a==b

False

In [18]:
def bb(a):
    for i in a:
        if i==b[0]:
            return 1
        else :
            return 0

In [19]:
print(bb(a))

0


In [21]:
import numpy as np

In [22]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [32]:
for i,p in enumerate(a):
    for j,q in enumerate(p):
        print(p)
        break

[1 2 3]
[1 2 3]
[1 2 3]


In [34]:
c = [1,1,2]

In [35]:
c.state()

AttributeError: 'list' object has no attribute 'state'

In [37]:
if c[3]==None:
    print(1)

IndexError: list index out of range

In [38]:
a = {1:2}

In [43]:
for i in a:
    print(a[i])

2
